# Generated by Django 5.0.6 on 2024-06-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('year_founded', models.IntegerField()),
                ('industry', models.CharField(max_length=255)),
                ('employees', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('linkedin_url', models.CharField(max_length=255)),
                ('current_employees', models.IntegerField()),
            ],
        ),
    ]
